language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ffion/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ffion/react-test npm test

after_success:
  - docker build -t ffion/multi-client ./client
  - docker build -t ffion/multi-nginx ./nginx
  - docker build -t ffion/multi-server ./server
  - docker build -t ffion/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pawssword-stdin

- docker push ffion/multi-client
- docker push ffion/multi-nginx
- docker push ffion/multi-server
- docker push ffion/multi-worker